# Generated by Django 3.0.6 on 2020-05-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20200524_0901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='project',
            name='img_name',
            field=models.ImageField(upload_to='college/img'),
        ),
    ]
