# Generated by Django 3.0.6 on 2020-05-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20200524_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img_name',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
