# Generated by Django 3.0.6 on 2020-05-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
